### ISSUE TITLE
Server crash every time a player enters the nether

### ISSUE THREAD

**Issue by MechanosG** [AzureDoom/AzureDoom-Doom-Fabric#13]
Seems to be related to Archviles?

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2021-02-03 00:59:03 MST
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.class_243.method_1034(Lnet/minecraft/class_241;)Lnet/minecraft/class_243;
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9)
    at mod.azure.doom.entity.projectiles.entity.ArchvileFiring.tick(ArchvileFiring.java:122)
    at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
    at net.minecraft.world.World.tickEntity(World:561)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
    at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:312)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
    at net.minecraft.server.MinecraftServer.handler$bgo000$modifiedRunLoop(MinecraftServer:6310)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: doom:archvile_firing (mod.azure.doom.entity.projectiles.entity.ArchvileFiring)
  Entity ID: 212
  Entity Name: entity.doom.archvile_firing
  Entity's Exact location: -74.36, 32.00, 122.96
  Entity's Block location: World: (-75,32,122), Chunk: (at 5,2,10 in -5,7; contains blocks -80,0,112 to -65,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[0.0d,0.0d,0.0d],FallDistance:0.0f,Warmup:-1,Pos:[-74.3623815893575d,32.0d,122.96471702606124d],Fire:118s,Invulnerable:0b,Air:300s,OnGround:0b,PortalCooldown:0,UUID:[I;-816742544,868109959,-1904448738,1480719212],Rotation:[-68.29521f,0.0f],TinyTweaksFireType:"NORMAL"}

-- Affected level --
  All players: 1 total; [class_3222['GeneralGanja'/48, l='ServerLevel[world]', x=-20.20, y=39.00, z=48.39]]
  Chunk stats: ServerChunkCache: 2025
  Level dimension: minecraft:the_nether
  Derived: true
  Level spawn location: World: (160,69,144), Chunk: (at 0,4,0 in 10,9; contains blocks 160,0,144 to 175,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 58442017 game time, 62118450 day time
  Level name: world
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Level weather: Rain time: 23703 (now: false), thunder time: 121268 (now: false)
  Known server brands: Fabric/Gunpowder
  Level was modded: true
  Level storage version: 0x04ABD - Anvil

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_231, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 352321504 bytes (335 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
  CPUs: 4
  JVM Flags: 20 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xmx4G -Xms2G
  Mixins in Stacktrace: net.minecraft.class_3218:
                        carpet.mixins.ServerWorld_scarpetMixin (carpet.mixins.json)
                        uk.me.desert_island.rer.mixin.MixinServerWorld (roughlyenoughresources.mixins.json)
                        com.terraformersmc.cinderscapes.mixin.ServerWorldMixin (cinderscapes.mixins.json)
                        appeng.mixins.ServerWorldCustomItemEntityMixin (appliedenergistics2.mixins.json)
                        me.shedaniel.cloth.mixin.common.events.MixinServerWorld (cloth-common-events-v1.mixins.json)
                        fi.dy.masa.tellme.mixin.IMixinServerWorld (mixins.tellme.json)
                        me.jellysquid.mods.lithium.mixin.ai.nearby_entity_tracking.ServerWorldMixin (lithium.mixins.json)
                        paulevs.betternether.mixin.common.ServerWorldMixin (betternether.mixins.common.json)
                        carpet.mixins.ServerWorld_spawnChunksMixin (carpet.mixins.json)
                        com.robertx22.library_of_exile.mixins.ServerWorldMixin (library_of_exile.mixins.json)
                        net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
                        ca.spottedleaf.starlight.mixin.common.world.ServerWorldMixin (starlight.mixins.json)
                        dev.onyxstudios.cca.mixin.chunk.common.MixinServerWorld (mixins.cardinal_components_chunk.json)
                        dev.onyxstudios.cca.mixin.world.common.MixinServerWorld (mixins.cardinal_components_world.json)
                        carpet.mixins.ServerWorld_onePlayerSleepingMixin (carpet.mixins.json)
                        io.github.gunpowder.mixin.sleepvote.ServerWorldMixin_SleepVote (mixins.sleepvote.gunpowder.json)
                        carpet.mixins.ServerWorld_fakePlayersMixin (carpet.mixins.json)
                        io.github.gunpowder.mixin.base.ServerWorldMixin_Base (mixins.base.gunpowder.json)
                        dev.hephaestus.tweaks.mixin.world.TickMore (tweaks.mixins.json)
                        dan200.computercraft.mixin.MixinServerWorld (computercraft.mixins.json)
                        net.adventurez.mixin.ServerWorldMixin (adventurez.mixins.json)
                        dev.onyxstudios.cca.mixin.entity.common.MixinServerWorld (mixins.cardinal_components_entity.json)
                        me.jellysquid.mods.lithium.mixin.alloc.world_ticking.ServerWorldMixin (lithium.mixins.json)
                        me.jellysquid.mods.lithium.mixin.world.tick_scheduler.ServerWorldMixin (lithium.mixins.json)
                        com.github.chainmailstudios.astromine.mixin.ServerWorldMixin (astromine.mixins.json)
                        carpet.mixins.ServerWorld_tickMixin (carpet.mixins.json)
                        me.jellysquid.mods.lithium.mixin.alloc.chunk_random.ServerWorldMixin (lithium.mixins.json)
                        net.minecraft.class_1937:
                        ca.spottedleaf.starlight.mixin.common.world.WorldMixin (starlight.mixins.json)
                        me.jellysquid.mods.lithium.mixin.ai.nearby_entity_tracking.WorldMixin (lithium.mixins.json)
                        dev.onyxstudios.cca.mixin.world.common.MixinWorld (mixins.cardinal_components_world.json)
                        ninjaphenix.chainmail.mixins.WorldMixin (chainmail.common.mixins.json)
                        net.fabricmc.fabric.mixin.event.lifecycle.WorldMixin (fabric-lifecycle-events-v1.mixins.json)
                        me.jellysquid.mods.lithium.mixin.alloc.chunk_random.WorldMixin (lithium.mixins.json)
                        dev.onyxstudios.cca.mixin.block.common.MixinWorld (mixins.cardinal_components_block.json)
                        draylar.magna.mixin.WorldMixin (magna.mixins.json)
                        me.jellysquid.mods.lithium.mixin.world.chunk_access.WorldMixin (lithium.mixins.json)
                        dan200.computercraft.mixin.MixinWorld (computercraft.mixins.json)
                        li.cil.tis3d.common.mixin.ChunkUnloadMixin (tis3d.mixins.common.json)
                        carpet.mixins.World_tickMixin (carpet.mixins.json)
                        carpet.mixins.World_scarpetPlopMixin (carpet.mixins.json)
                        carpet.mixins.World_fillUpdatesMixin (carpet.mixins.json)
                        carpet.mixins.World_movableTEMixin (carpet.mixins.json)
                        net.minecraft.server.MinecraftServer:
                        com.kqp.tcrafting.mixin.accessor.MinecraftServerResourceAccessor (tcrafting.mixins.json)
                        carpet.mixins.MinecraftServer_coreMixin (carpet.mixins.json)
                        ru.betterend.mixin.common.MinecraftServerMixin (betterend.mixins.common.json)
                        net.szum123321.textile_backup.mixin.MinecraftServerMixin (textile_backup.mixins.json)
                        badasintended.megane.runtime.mixin.MMinecraftServer (megane-runtime.mixins.json)
                        paulevs.betternether.mixin.common.MinecraftServerMixin (betternether.mixins.common.json)
                        com.telepathicgrunt.blame.mixin.MinecraftServerMixin (blame.mixins.json)
                        com.yungnickyoung.minecraft.bettercaves.mixin.MixinMinecraftServer (bettercaves.mixins.json)
                        carpet.mixins.MinecraftServer_tickspeedMixin (carpet.mixins.json)
                        net.sssubtlety.automated_crafting.mixin.MinecraftServerMixin (automated_crafting.mixins.json)
                        dev.onyxstudios.cca.mixin.scoreboard.MixinMinecraftServer (mixins.cardinal_components_scoreboard.json)
                        uk.me.desert_island.rer.mixin.MixinMinecraftServer (roughlyenoughresources.mixins.json)
                        dev.onyxstudios.cca.mixin.level.common.MixinMinecraftServer (mixins.cardinal_components_level.json)
                        net.fabricmc.fabric.mixin.resource.loader.MinecraftServerMixin (fabric-resource-loader-v0.mixins.json)
                        io.github.gunpowder.mixin.base.MinecraftServerMixin_Base (mixins.base.gunpowder.json)
                        net.fabricmc.fabric.mixin.event.lifecycle.MinecraftServerMixin (fabric-lifecycle-events-v1.mixins.json)
                        badasintended.monopoly.mixin.MinecraftServerMixin (monopoly.mixins.json)
                        carpet.mixins.MinecraftServer_scarpetMixin (carpet.mixins.json)
                        adudecalledleo.lionutils.internal.mixin.MinecraftServerMixin (lionutils.internal.mixins.json)
                        dan200.computercraft.mixin.MinecraftServerAccess (computercraft.mixins.json)
                        net.szum123321.textile_backup.mixin.MinecraftServerSessionAccessor (textile_backup.mixins.json)
                        vazkii.patchouli.mixin.AccessorMinecraftServer (patchouli.mixins.json)
  Suspected Mods: Doom Fabric (doom)
  Fabric Mods: advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
               adventurez: AdventureZ 1.1.5
               allure: Allure 1.2.8
               amecs: Amecs 1.3.2+mc.1.16.3
               amecsapi: Amecs API 1.1.1+mc1.16-rc1
               ancientgateways: Ancient Gateways 1.0.2
               anonymize: Anonymize 0.1.0
               aopalliance_aopalliance: aopalliance 1.0
               appleskin: AppleSkin 1.0.11
               appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
               artifice: Artifice 0.13.2+1.16.3
               astromine: Astromine 1.11.5+fabric-1.16.5
               astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
               astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
               astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
               astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
               astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
               autoconfig1u: Auto Config v1 Updated 3.3.1
               automated_crafting: Automated Crafting 1.3.14+MC1.16.2-1.16.4
               automotons: Automotons 1.0.1
               balance_of_exile: Balance of Exile 1.0.3
               bedrockify: BedrockIfy 0.2.0
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               bettereating: Better Eating 0.2.0
               betterend: Better End 0.8.0-beta
               bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
               betternether: Better Nether 5.0.4
               betterstones: Better Stones 0.0.4
               biomemakeover: Biome Makeover 1.16.4-1.1.5
               blade: Blade 2.0.0
               blame: Blame 2.3.0
               blast: BLAST 1.5
               blockus: Blockus 2.0.1+1.16.4
               blue_endless_jankson: jankson 1.2.0
               buildersblocks: Builders' Blocks 1.16.3-beta.8
               campanion: Campanion 1.3.1+build.51
               cardinal-components: Cardinal Components API 2.7.9
               cardinal-components-base: Cardinal Components API (base) 2.7.10
               cardinal-components-block: Cardinal Components API (blocks) 2.7.10
               cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
               cardinal-components-entity: Cardinal Components API (entities) 2.7.10
               cardinal-components-item: Cardinal Components API (items) 2.7.10
               cardinal-components-level: Cardinal Components API (world saves) 2.7.10
               cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.9
               cardinal-components-util: Cardinal Components API (utilities) 2.7.10
               cardinal-components-world: Cardinal Components API (worlds) 2.7.10
               carpet: Carpet Mod in Fabric 1.4.24
               chainmail: Chainmail 0.5.0
               cinderscapes: Cinderscapes 1.3.0+build.51
               cleancut: CleanCut mc1.16-2.1-fabric
               clearview: Clear View 2.1
               climbable: Climbable 0.2.0
               cloth-armor-api-v1: Cloth Armor API v1 1.4.8
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-common-events-v1: Cloth Common Events v1 1.4.8
               cloth-config2: Cloth Config v4 4.8.3
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
               cloth-utils-v1: Cloth Utils v1 1.4.5
               coloredcraftingstations: ColoredCraftingStations 1.0.1
               com_electronwill_night-config_core: core 3.6.0
               com_electronwill_night-config_toml: toml 3.6.0
               com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
               com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
               com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
               com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
               com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
               com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
               com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
               com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
               com_google_inject_guice: guice 4.2.3
               com_typesafe_config: config 1.4.0
               com_udojava_evalex: EvalEx 2.5
               computercraft: CC:T for Fabric 1.91.2
               convenient-mobgriefing: Convenient mobGriefing 1.1.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               couplings: Couplings 1.3.3
               cpas: conveniently placed armor slots 1.2.0+1.16.4
               creeperspores: Creeper Spores 1.4.1
               croptopia: Croptopia 1.0.5-1.16.3-FABRIC
               crowdin-translate: CrowdinTranslate 1.2
               crowmap: Crowmap 1.0.1
               cullparticles: Cull Particles 2.0
               curios: Curios API 0.0.10-1.16.3
               customspawns: Custom Spawns 0.1.2
               dankstorage: Dank Storage 1.9a-1.16.3
               dawn: Dawn API 1.6
               demeter: Demeter 2.0.0
               doom: Doom Fabric 3.9.3
               earthtojavamobs: Earth2Java 1.5.0+1.16.4
               edit_sign: Edit Sign 2.1.3
               enchant_giver: Enchant Giver 1.0.2
               expandedstorage: ExpandedStorage 5.6.31
               ezpas: Ezpas 1.2.3-1.16.2
               fabric: Fabric API 0.28.3+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabricloader: Fabric Loader 0.10.8
               fancymenu: FancyMenu 1.6.0
               fastbench: FastBench 2.3
               fastfurnace: FastFurnace 2.3
               fatxporbs: Fat Experience Orbs 0.0.9
               fermion: Fermion 2.9.217
               fermion-modkeys: Fermion Modifier Keys 1.10.218
               fermion-orientation: Fermion Orientation 1.2.217
               fermion-varia: Fermion Varia 2.6.217
               fiber: fiber 0.23.0-2
               flonters: Flonters 1.1.1+1.16.2
               geckolib3: Geckolib 3.0.3
               glassdoor: Glass Doors 1.5.0-1.16
               glowingbeds: Glowing Beds 1.2.1
               go-fish: Go Fish 1.1.0-beta-1.16.4
               goml: Get Off My Lawn 1.1.0
               gottaclimbfast: Gotta Climb Fast! 1.0
               gravestones: Gravestones v1.7
               gunpowder-base: Gunpowder 0.3.4+1.16.4
               gunpowder-sleepvote: Gunpowder SleepVote 1.0.3+gunpowder.0.3.1.mc.1.16.4
               horsestatsvanilla: Horse Stats Vanilla 4.1.4
               hplus: Hopper Plus 1.0.10
               iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
               indrev: Industrial Revolution 1.7.11-BETA
               inmis: Inmis 1.3.1-1.16.2
               inventorytabs: Inventory Tabs 0.3.0-1.16.4
               itemflexer: ItemFlexer 1.1.3
               jankson: Jankson 3.0.1+j1.2.0
               javax_inject_javax_inject: javax.inject 1
               javax_vecmath_vecmath: vecmath 1.5.2
               killerbee: KillerBee 1.0
               kirin: Kirin UI 1.7-1.16.2
               konkrete: Konkrete 1.1.0
               krypton: Krypton 0.1.1
               kubejs: KubeJS 1.5.5
               lapisreserve: Lapis Reserve 1.0.6
               launchersmod: Launchers 3.1.0
               lazydfu: LazyDFU 0.1.1
               leadvillagers: Lead Villagers 2.1.0+mc1.16.1
               libblockattributes: LibBlockAttributes 0.8.4
               libblockattributes_core: LibBlockAttributes (Core) 0.8.5
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
               libblockattributes_items: LibBlockAttributes (Items) 0.8.5
               libgui: LibGui 3.2.1+1.16.3
               library_of_exile: Library of Exile 1.0.6
               libstructure: LibStructure 1.5
               linkedstorage: Linked Storage 1.3.11-1.16
               lionutils: LionUtils 7.0.0+1.16
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loud_leads: Loud Leads 1.0.1+mc1.16.4
               maelstrom_library: Maelstrom Library 0.4.1
               magna: Magna 1.4.3-1.16.2
               mambience: MAmbience 2.1.0+1.16.2
               materialisation: Materialisation 3.0.3
               mcda: MC Dungeons Armors 0.9.3
               mcdw: MC Dungeons Weapons 2.6.0
               megane: megane 3.1.0+1.16.4
               megane-api: megane-api 3.1.0+1.16.4
               megane-impl: megane-impl 3.1.0+1.16.4
               megane-runtime: megane-runtime 3.1.0+1.16.4
               microconfig: Microconfig 1.0.3
               minecraft: Minecraft 1.16.4
               mixintrace: MixinTrace 1.0.0
               mmorpg: Age of Exile 1.7.8
               mo_glass: Mo Glass 1.5-MC1.16.4
               mobs_attempt_parkour: Mobs Attempt Parkour 0.2.1-1.16.3
               modern_industrialization: Modern Industrialization 0.3.7
               monopoly: monopoly 1.2.1+minecraft-1.16.2
               monster-in-the-closet: Monsters in the Closet 1.0.0
               moreberries: More Berries 1.3.4
               moreblocksmod: More Blocks Mod 0.1.2.0
               muffle: Muffle 0.1.1
               mysql_mysql-connector-java: mysql-connector-java 5.1.46
               mythicmetals: Mythic Metals 0.9.5
               nbtcrafting: NBT Crafting 2.0.3+mc1.16.4
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               nourish: Nourish 1.1.1
               org_apache_commons_commons-compress: commons-compress 1.19
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_exposed_exposed-core: exposed-core 0.27.1
               org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.27.1
               org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.27.1
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_joml_joml: joml 1.10.0
               org_postgresql_postgresql: postgresql 42.2.2
               org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
               org_tukaani_xz: xz 1.8
               org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
               org_yaml_snakeyaml: snakeyaml 1.26
               overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
               patchouli: Patchouli 1.16.4-48-FABRIC
               piglib: Piglib 1.0.1
               polish: Polish 1.0.3
               polymorph: Polymorph 0.0.5-1.16.3
               pugh_lib: Pugh Lib 1.0.2
               randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               respawnablepets: Respawnable Pets 1.16.4-1
               retail: Retail 0.1.0
               rocks: This Rocks! 1.2.2
               roughlyenoughitems: Roughly Enough Items 5.8.10
               roughlyenoughitems-api: REI (API) 5.8.10
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
               roughlyenoughitems-runtime: REI (Runtime) 5.8.10
               roughlyenoughresources: Roughly Enough Resources 2.1.3
               rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
               sandwichable: Sandwichable 1.1.2
               shelf: Shelf 1.0.0
               simpledrawers: Simple Drawers 1.8.0-1.16.3
               slotlink: slotlink 2.2.0+1.16.4
               smithee: Smithee 0.1.5
               smoothboot: Smooth Boot 1.16-1.3.1
               snowdrift: Snowdrift 1.2.1-1.16.4
               special-circumstances: Special Circumstances 1.8.217
               spinnery: Spinnery 3.1.13
               starlight: Starlight 0.0.3
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               strongandfairanvils: Strong and Fair Anvils 0.3.0+1.16
               tacobell: Taco Bell 1.1.1
               tcrafting: TCrafting 1.2.1-1.16.4
               team_reborn_energy: Energy 0.1.1
               tellme: TellMe 0.9.1-beta.1
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.4
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.3
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               terrestria: Terrestria 2.1.5+build.28
               textile_backup: Textile Backup 2.0.1-1.16.3
               the_loved_ones: The Loved Ones 1.1.0+1.16.4
               tinytweaks: TinyTweaks 1.1.2
               tis3d: TIS-3D 1.6.1
               trinkets: Trinkets 2.6.7
               unforgivingvoid: Unforgiving Void 2.0.0
               universalcomponents: Universal Components 0.7.3+1.16.2
               veggie_way: The Veggie Way 1.0.35
               villagernames: Villager Names 1.6.0
               visualoverhaul: VisualOverhaul 1.0.0
               waila: Hwyla 1.9.22
               wild_explorer: Wild Explorer 1.3
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               woodenhoppers: Wooden Hoppers 1.0.0
               woods_and_mires: Woods and Mires 1.0.4+1.16.3
               wrenchable: Wrenchable 1.0.0+1.16.1
               ynet: YNet 0.2.0
               yosbr: YOSBR 0.1.1
               yungsapi: YUNG's API 1.16.4-Fabric-1
               zoob: Monster Of The Ocean Depths 2.5.0
  Player Count: 1 / 20; [class_3222['GeneralGanja'/48, l='ServerLevel[world]', x=-20.20, y=39.00, z=48.39]]
  Data Packs: vanilla (incompatible), fabric/allure, fabric/ancientgateways, fabric/appliedenergistics2, fabric/automated_crafting, fabric/balance_of_exile (incompatible), fabric/bedrockify, fabric/betterend, fabric/betternether, fabric/betterstones, fabric/biomemakeover, fabric/blast, fabric/blockus, fabric/buildersblocks, fabric/campanion, fabric/cinderscapes, fabric/computercraft (incompatible), fabric/creeperspores, fabric/croptopia, fabric/curios, fabric/dankstorage, fabric/demeter, fabric/expandedstorage, fabric/fabric-tool-attribute-api-v1, fabric/glassdoor, fabric/goml, fabric/hplus, fabric/iamverysmart, fabric/indrev, fabric/inmis, fabric/kubejs (incompatible), fabric/linkedstorage, fabric/materialisation, fabric/mmorpg, fabric/mo_glass, fabric/modern_industrialization, fabric/moreberries, fabric/muffle, fabric/mythicmetals, fabric/nourish, fabric/respawnablepets, fabric/rocks, fabric/sandwichable, fabric/simpledrawers, fabric/slotlink, fabric/strongandfairanvils, fabric/tacobell, fabric/terrestria, fabric/tinytweaks, fabric/tis3d (incompatible), fabric/trinkets, fabric/veggie_way, fabric/wild_explorer, fabric/woodenhoppers, fabric/woods_and_mires, fabric/ynet, fabric/zoob, fabric/adventurez, fabric/automotons (incompatible), fabric/coloredcraftingstations, fabric/doom, fabric/earthtojavamobs, fabric/ezpas, fabric/flonters, fabric/go-fish, fabric/gravestones, fabric/killerbee, fabric/launchersmod, fabric/mcda, fabric/mcdw, fabric/moreblocksmod, fabric/retail, fabric/smithee, fabric/wolveswitharmor, fabric/astromine-core, fabric/astromine-discoveries, fabric/astromine-foundations, fabric/astromine-technologies, fabric/astromine-transportations, fabric/piglib, fabric/shelf
  Is Modded: Definitely; Server brand changed to 'Fabric/Gunpowder'
  Type: Dedicated Server (map_server.txt)
```

**Comment by AzureDoom** [comment]
This should be fixed in the next update

**Comment by MechanosG** [comment]
Cool, thanks dude.
