### ISSUE TITLE
Shotgun does not reload

### ISSUE THREAD

**Issue by Noaaan** [AzureDoom/AzureDoom-Doom-Fabric#5]
The Shotgun  works creative mode without ammo, but it does not work with ammo in the inventory.
Whenever you try to reload, it returns a NullPointerException  
Here is the stacktrace:  
[12:07:39] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.class_2945.method_12778(class_2945.java:124) ~[intermediary-server.jar:?]
        at mod.azure.doom.entity.projectiles.ShotgunShellEntity.initFromStack(ShotgunShellEntity.java:172) ~[Doom-Mod-Fabric-1.16.3-3.1.5.jar:?]
        at mod.azure.doom.item.ammo.ShellAmmo.createArrow(ShellAmmo.java:33) ~[Doom-Mod-Fabric-1.16.3-3.1.5.jar:?]
        at mod.azure.doom.item.weapons.Shotgun.method_7840(Shotgun.java:75) ~[Doom-Mod-Fabric-1.16.3-3.1.5.jar:?]
        at net.minecraft.class_1799.method_7930(class_1799.java:499) ~[intermediary-server.jar:?] ...

**Comment by AzureDoom** [comment]
This is fixed. Will be out in the next update!
